spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
cloud:
  aws:
    region: ap-northeast-1
    credentials:
      accessKey: AKIAIHZ3QS6LY3SBF7FQ
      secretKey: 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
  s3:
    url: https://s3.ap-northeast-1.amazonaws.com
    bucketName: studymaterefer