spring:
  datasource:
        url: "secret"
        username: secret
        password: secret
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
cloud:
  aws:
    region: ap-northeast-1
    credentials:
      accessKey: secret
      secretKey: secret
  s3:
    url: secret
    bucketName: studymaterefer


    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy