spring:
    datasource:
        url: "jdbc:mysql://ndgndg91.synology.me:3307/studyMate?useSSL=false&serverTimezone=UTC"
        username: yjg
        password: yjg
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            
    mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp