spring:
    datasource:
        url: "secret"
        username: secret
        password: secret
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp